sudo: required
services:
    - docker
before_install:
    - docker-compose run combinator-composer-update
    - docker-compose up -d --build combinator-dev-webserver combinator-db-migrations combinator-dev-db
script:
    - ./tests/run.sh --all
after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
          docker build --tag combinator-api . ;
          docker tag combinator-api registry.heroku.com/$HEROKU_APP/web ;
          docker login --username=_ --password="$HEROKU_API_KEY" registry.heroku.com ;
          docker push registry.heroku.com/$HEROKU_APP/web ;
      fi
