language: php
php:
    - '7.1'
sudo: required
services:
    - docker
before_install:
    - docker-compose run composer
    - docker-compose up -d combinator-api combinator-db
script:
    - ./tests/run.sh --all
