sudo: required
services:
    - docker
before_install:
    - docker-compose run composer
    - docker-compose up -d --build combinator-api combinator-db
script:
    - echo 'hey i think that worked'
    #- ./tests/run.sh --all
after_success:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
          docker build --tag combinator-api . ;
          docker tag combinator-api registry.heroku.com/$HEROKU_APP/web ;
          docker login --username=_ --password="$HEROKU_API_KEY" registry.heroku.com ;
          docker push registry.heroku.com/$HEROKU_APP/web ;
      fi
