version: '2'
services:
  combinator-dev-webserver:
    build: ./
    volumes:
      - ./:/var/www
    environment:
      - PORT=80
      - APP_DB_HOST=combinator-db
      - APP_DB_PORT=5432
      - APP_DB_NAME=combinator
      - APP_DB_USER=postgres
      - APP_DB_PASSWORD=postgres
    ports:
      - "8080:80"
    links:
      - combinator-db
    container_name: combinator-dev-webserver
    networks:
      - dev
  combinator-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=combinator
    ports:
      - "5000:5432"
  composer:
    image: composer/composer
    volumes:
      - ./:/app
    command: update
    depends_on:
      - combinator-dev-webserver

networks:
  dev:
