version: '2'
services:

  combinator-dev-webserver:
    build: ./
    volumes:
      - ./:/var/www
    environment:
      - PORT=80
      - APP_DB_HOST=combinator-db
      - APP_DB_PORT=5432
      - APP_DB_NAME=combinator
      - APP_DB_USER=postgres
      - APP_DB_PASSWORD=postgres
    ports:
      - "8080:80"
    links:
      - combinator-dev-db
    container_name: combinator-dev-webserver
    networks:
      - dev
  combinator-dev-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=combinator
    ports:
      - "5000:5432"
    networks:
      - dev

  combinator-composer-update:
    image: composer/composer
    volumes:
      - ./:/app
    command: update
    depends_on:
      - combinator-dev-webserver

  combinator-db-migrations:
    image: php:7.1.4-cli
    volumes:
      - ./:/app
    working_dir: /app
    command: idkyet
    environment:
      - PHINX_APP_DB_HOST=combinator-dev-db
      - PHINX_APP_DB_PORT=5432
      - PHINX_APP_DB_NAME=combinator
      - PHINX_APP_DB_USER=postgres
      - PHINX_APP_DB_PASSWORD=postgres
    links:
      - combinator-dev-db
    depends_on:
      - combinator-dev-db

networks:
  dev:
